"""Shared application constants."""

from typing import Any

CODE_EXPIRY_MINUTES: int = 10
ACCESS_TOKEN_EXPIRE_MINUTES: int = 60
REFRESH_TOKEN_EXPIRE_DAYS: int = 7
ASSESSMENT_QUESTION_COUNT: int = 25
DAILY_CHECKIN_QUESTION_COUNT: int = 8
WEEKLY_CHECKIN_QUESTION_COUNT: int = 10
MONTHLY_CHECKIN_QUESTION_COUNT: int = 13

CONDITIONS: list[str] = ["Optimal", "Stable", "Strained", "High Risk", "Critical"]
DIMENSIONS: list[str] = ["PC", "MR", "MC", "PA", "RC"]
REVERSE_SCORED_QUESTION_IDS: set[str] = {
    "dc_3",
    "wc_3",   # stress level this week (weekly)
    "mc_5",
    "mc_13",  # outside stress (monthly)
}
REVERSE_SCORED_QUESTION_TEXTS: set[str] = {
    "How frequently do you experience high stress?",
    "How often do you eat processed or fast foods?",
    "How fatigued do you feel after a typical workday?",
    "How much outside stress affects your daily life?",
}
CONDITION_THRESHOLDS: dict[str, int] = {
    "Optimal": 85,
    "Stable": 70,
    "Strained": 55,
    "High Risk": 40,
}

ORGANIZATION_ROLE_OPTIONS: dict[str, list[str]] = {
    "Global Tech Solutions": [
        "Product Design",
        "Software Engineer",
        "Engineering Manager",
        "Sales Executive",
        "HR Manager",
    ],
    "Dominion Wellness Solutions": [
        "Performance Coach",
        "Operations Lead",
        "Sales Executive",
        "Support Specialist",
        "Product Manager",
    ],
    "Company A": [
        "Sales Executive",
        "Senior Executive",
        "Team Lead",
        "Operations Manager",
        "Department Head",
    ],
    "Northstar Health Group": [
        "Wellness Coordinator",
        "Clinical Operations Analyst",
        "Account Manager",
        "Support Specialist",
        "Regional Lead",
    ],
}

ORGANIZATION_OPTIONS: list[str] = list(ORGANIZATION_ROLE_OPTIONS.keys())

ORGANIZATION_DEPARTMENT_OPTIONS: dict[str, list[str]] = {
    "Global Tech Solutions": [
        "Product Design",
        "Engineering",
        "Sales",
        "Human Resources",
    ],
    "Dominion Wellness Solutions": [
        "Performance Operations",
        "Product",
        "Client Success",
        "Sales",
    ],
    "Company A": [
        "Senior Executive",
        "Operations",
        "Sales",
        "Administration",
    ],
    "Northstar Health Group": [
        "Clinical Operations",
        "Wellness Programs",
        "Account Management",
        "Regional Support",
    ],
}

ORGANIZATION_TEAM_OPTIONS: dict[str, dict[str, list[str]]] = {
    "Global Tech Solutions": {
        "Product Design": ["Product Design", "UX Research", "Brand Design"],
        "Engineering": ["Platform", "Mobile", "Data Infrastructure"],
        "Sales": ["Enterprise Sales", "SMB Sales", "Partnerships"],
        "Human Resources": ["Talent", "People Operations", "Learning"],
    },
    "Dominion Wellness Solutions": {
        "Performance Operations": ["OPS Strategy", "Recovery Programs", "Field Coaching"],
        "Product": ["AI Product", "Mobile Experience", "Platform"],
        "Client Success": ["Customer Success", "Implementation", "Support"],
        "Sales": ["Business Development", "Account Executive", "Partnerships"],
    },
    "Company A": {
        "Senior Executive": ["Senior Executive", "Leadership Office"],
        "Operations": ["Operations", "Logistics"],
        "Sales": ["Retail Sales", "B2B Sales"],
        "Administration": ["Admin Support", "Office Management"],
    },
    "Northstar Health Group": {
        "Clinical Operations": ["Care Delivery", "Clinical Support"],
        "Wellness Programs": ["Program Delivery", "Community Outreach"],
        "Account Management": ["Client Accounts", "Strategic Accounts"],
        "Regional Support": ["North Region", "South Region"],
    },
}

ORGANIZATION_METADATA: dict[str, dict[str, str]] = {
    "Global Tech Solutions": {"code": "GT-9921"},
    "Dominion Wellness Solutions": {"code": "DWS-2401"},
    "Company A": {"code": "CA-1001"},
    "Northstar Health Group": {"code": "NHG-4810"},
}

APP_VERSION: str = "DWS Performance v2.4.1"

QUESTION_BANK: list[dict[str, Any]] = [
    {
        "text": "How would you describe your energy on most days?",
        "driver": "RC",
        "response_type": "scale",
        "options": ["Very Low", "Low", "Average", "High", "Very High"],
        "weight": 1.0,
        "order": 1,
    },
    {
        "text": "How well can you stay focused during your workday?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very Poor", "Poor", "Average", "Good", "Excellent"],
        "weight": 1.0,
        "order": 2,
    },
    {
        "text": "How frequently do you experience high stress?",
        "driver": "MR",
        "response_type": "multiple_choice",
        "options": ["Never", "Rarely", "Often", "Very often"],
        "weight": 1.0,
        "order": 3,
    },
    {
        "text": "How stable are your emotions during pressure or challenges?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very Unstable", "Unstable", "Neutral", "Stable", "Very Stable"],
        "weight": 1.0,
        "order": 4,
    },
    {
        "text": "How confident are you in handling unexpected problems?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Not Confident", "Low", "Moderate", "Confident", "Very Confident"],
        "weight": 1.0,
        "order": 5,
    },
    {
        "text": "How motivated do you feel toward your daily responsibilities?",
        "driver": "PA",
        "response_type": "scale",
        "options": ["Very Low", "Low", "Average", "High", "Very High"],
        "weight": 1.0,
        "order": 6,
    },
    {
        "text": "How well do you recover mentally after stressful situations?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very Poor", "Poor", "Average", "Good", "Excellent"],
        "weight": 1.0,
        "order": 7,
    },
    {
        "text": "How rested do you usually feel after sleep?",
        "driver": "RC",
        "response_type": "scale",
        "options": ["Very Tired", "Tired", "Okay", "Rested", "Very Rested"],
        "weight": 1.0,
        "order": 8,
    },
    {
        "text": "How aligned do you feel with your priorities and direction?",
        "driver": "PA",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Slightly", "Very", "Completely"],
        "weight": 1.0,
        "order": 9,
    },
    {
        "text": "How would you rate your overall health?",
        "driver": "PC",
        "response_type": "scale",
        "options": ["Poor", "Fair", "Good", "Very Good", "Excellent"],
        "weight": 1.0,
        "order": 10,
    },
    {
        "text": "How many hours do you usually sleep on weeknights?",
        "driver": "RC",
        "response_type": "multiple_choice",
        "options": ["< 4H", "4-5H", "6-7H", "7-8H", "8H+"],
        "weight": 1.0,
        "order": 11,
    },
    {
        "text": "How consistent is your sleep schedule?",
        "driver": "RC",
        "response_type": "scale",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 12,
    },
    {
        "text": "How consistent is your physical activity?",
        "driver": "PC",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Slightly consistent", "Consistent", "Very consistent"],
        "weight": 1.0,
        "order": 13,
    },
    {
        "text": "How often do you eat balanced meals?",
        "driver": "PC",
        "response_type": "scale",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 14,
    },
    {
        "text": "How often do you eat processed or fast foods?",
        "driver": "PC",
        "response_type": "scale",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 15,
    },
    {
        "text": "How often do you eat fruits and vegetables?",
        "driver": "PC",
        "response_type": "scale",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 16,
    },
    {
        "text": "How well do you stay hydrated during the day?",
        "driver": "PC",
        "response_type": "scale",
        "options": ["Very Poor", "Poor", "Average", "Good", "Excellent"],
        "weight": 1.0,
        "order": 17,
    },
    {
        "text": "How often do you practice stress management (meditation, breathing, etc.)?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 18,
    },
    {
        "text": "How often do you take breaks during long work periods?",
        "driver": "MC",
        "response_type": "scale",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 19,
    },
    {
        "text": "How fatigued do you feel after a typical workday?",
        "driver": "RC",
        "response_type": "scale",
        "options": ["None", "Low", "Moderate", "High", "Extreme"],
        "weight": 1.0,
        "order": 20,
    },
    {
        "text": "How manageable is your current workload?",
        "driver": "PA",
        "response_type": "scale",
        "options": ["Overwhelming", "Heavy", "Manageable", "Light", "Very Light"],
        "weight": 1.0,
        "order": 21,
    },
    {
        "text": "How supported and connected do you feel in your work environment?",
        "driver": "MC",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Slightly", "Very", "Extremely"],
        "weight": 1.0,
        "order": 22,
    },
    {
        "text": "How often do you receive recognition for your work?",
        "driver": "MC",
        "response_type": "scale",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 23,
    },
    {
        "text": "How connected do you feel with your team or peers?",
        "driver": "MC",
        "response_type": "scale",
        "options": ["Very Isolated", "Somewhat Isolated", "Neutral", "Connected", "Very Connected"],
        "weight": 1.0,
        "order": 24,
    },
    {
        "text": "How much outside stress affects your daily life?",
        "driver": "MC",
        "response_type": "scale",
        "options": ["None", "Low", "Moderate", "High", "Extreme"],
        "weight": 1.0,
        "order": 25,
    },
]

DAILY_CHECKIN_QUESTION_BANK: list[dict[str, Any]] = [
    {
        "id": "dc_1",
        "text": "How is your energy level right now?",
        "driver": "RC",
        "response_type": "scale",
        "options": ["Very low", "Low", "High", "Very high"],
        "weight": 1.0,
        "order": 1,
    },
    {
        "id": "dc_2",
        "text": "How focused do you feel right now?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very low", "Low", "High", "Very high"],
        "weight": 1.0,
        "order": 2,
    },
    {
        "id": "dc_3",
        "text": "How high is your stress level right now?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very low", "Low", "High", "Very high"],
        "weight": 1.0,
        "order": 3,
    },
    {
        "id": "dc_4",
        "text": "How motivated do you feel today?",
        "driver": "PA",
        "response_type": "scale",
        "options": ["Very low", "Low", "About average", "High", "Very high"],
        "weight": 1.0,
        "order": 4,
    },
    {
        "id": "dc_5",
        "text": "How many hours did you sleep last night?",
        "driver": "RC",
        "response_type": "multiple_choice",
        "options": ["Less than 4", "4-5", "6-7", "7-8", "More than 8"],
        "weight": 1.0,
        "order": 5,
    },
    {
        "id": "dc_6",
        "text": "How would you rate your sleep quality last night?",
        "driver": "RC",
        "response_type": "multiple_choice",
        "options": ["Very poor", "Poor", "Good", "Excellent"],
        "weight": 1.0,
        "order": 6,
    },
    {
        "id": "dc_7",
        "text": "How physically active have you been today?",
        "driver": "PC",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Light activity", "Moderate activity", "High activity"],
        "weight": 1.0,
        "order": 7,
    },
    {
        "id": "dc_8",
        "text": "Which best describes your meals yesterday?",
        "driver": "PC",
        "response_type": "multiple_choice",
        "options": [
            "Skipped meals or ate very little",
            "Mostly quick or processed foods",
            "A mix of balanced and quick meals",
            "Mostly balanced meals",
        ],
        "weight": 1.0,
        "order": 8,
    },
]


WEEKLY_CHECKIN_QUESTION_BANK: list[dict[str, Any]] = [
    {
        "id": "wc_1",
        "text": "How strong did you feel mentally this week?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very low", "Low", "Average", "High", "Very high"],
        "weight": 1.0,
        "order": 1,
    },
    {
        "id": "wc_2",
        "text": "How emotionally balanced did you feel this week?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very low", "Low", "Average", "High", "Very high"],
        "weight": 1.0,
        "order": 2,
    },
    {
        "id": "wc_3",
        "text": "How high was your stress level overall this week?",
        "driver": "MR",
        "response_type": "scale",
        "options": ["Very low", "Low", "High", "Very high"],
        "weight": 1.0,
        "order": 3,
    },
    {
        "id": "wc_4",
        "text": "How well did your actions align with your priorities this week?",
        "driver": "PA",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Slightly", "Very well", "Completely"],
        "weight": 1.0,
        "order": 4,
    },
    {
        "id": "wc_5",
        "text": "How consistent was your physical activity this week?",
        "driver": "PC",
        "response_type": "scale",
        "options": [
            "Very inconsistent",
            "Inconsistent",
            "Average",
            "Consistent",
            "Very consistent",
        ],
        "weight": 1.0,
        "order": 5,
    },
    {
        "id": "wc_6",
        "text": "How consistent was your sleep schedule this week?",
        "driver": "RC",
        "response_type": "scale",
        "options": [
            "Very inconsistent",
            "Inconsistent",
            "Average",
            "Consistent",
            "Very consistent",
        ],
        "weight": 1.0,
        "order": 6,
    },
    {
        "id": "wc_7",
        "text": "How consistent were your meals this week?",
        "driver": "PC",
        "response_type": "multiple_choice",
        "options": ["Very inconsistent", "Inconsistent", "Consistent", "Very consistent"],
        "weight": 1.0,
        "order": 7,
    },
    {
        "id": "wc_10",
        "text": "How often did you eat balanced meals this week?",
        "driver": "PC",
        "response_type": "multiple_choice",
        "options": ["Never", "1–2 days", "3–4 days", "5–6 days", "Every day"],
        "weight": 1.0,
        "order": 8,
    },
    {
        "id": "wc_8",
        "text": "How manageable was your workload this week?",
        "driver": "PA",
        "response_type": "multiple_choice",
        "options": ["Not manageable", "Difficult", "Manageable", "Easy", "Very easy"],
        "weight": 1.0,
        "order": 9,
    },
    {
        "id": "wc_9",
        "text": "How supported and connected did you feel this week?",
        "driver": "MC",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Slightly", "Very", "Extremely"],
        "weight": 1.0,
        "order": 10,
    },
]

MONTHLY_CHECKIN_QUESTION_BANK: list[dict[str, Any]] = [
    {
        "id": "mc_1",
        "text": "How would you rate your overall energy level this month?",
        "driver": "RC",
        "response_type": "multiple_choice",
        "options": ["Very low", "Low", "High", "Very high"],
        "weight": 1.0,
        "order": 1,
    },
    {
        "id": "mc_2",
        "text": "How would you rate your sleep quality this month?",
        "driver": "RC",
        "response_type": "multiple_choice",
        "options": ["Very poor", "Poor", "Good", "Excellent"],
        "weight": 1.0,
        "order": 2,
    },
    {
        "id": "mc_3",
        "text": "How consistent were your meals this month?",
        "driver": "PC",
        "response_type": "multiple_choice",
        "options": ["Very inconsistent", "Inconsistent", "Consistent", "Very consistent"],
        "weight": 1.0,
        "order": 3,
    },
    {
        "id": "mc_4",
        "text": "How well are you recovering after demanding days?",
        "driver": "RC",
        "response_type": "multiple_choice",
        "options": ["Very poorly", "Poorly", "Okay", "Well", "Very well"],
        "weight": 1.0,
        "order": 4,
    },
    {
        "id": "mc_5",
        "text": "How often have you felt mentally exhausted this month?",
        "driver": "MR",
        "response_type": "multiple_choice",
        "options": ["Never", "Rarely", "Often", "Very often"],
        "weight": 1.0,
        "order": 5,
    },
    {
        "id": "mc_6",
        "text": "How strong has your mental resilience been this month?",
        "driver": "MR",
        "response_type": "multiple_choice",
        "options": ["Very poorly", "Poorly", "Okay", "Well", "Very well"],
        "weight": 1.0,
        "order": 6,
    },
    {
        "id": "mc_7",
        "text": "How well are you managing stress overall?",
        "driver": "MR",
        "response_type": "multiple_choice",
        "options": ["Very poorly", "Poorly", "Okay", "Well", "Very well"],
        "weight": 1.0,
        "order": 7,
    },
    {
        "id": "mc_8",
        "text": "How motivated do you feel toward your responsibilities?",
        "driver": "PA",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
        "weight": 1.0,
        "order": 8,
    },
    {
        "id": "mc_9",
        "text": "How aligned do you feel with your direction and priorities this month?",
        "driver": "PA",
        "response_type": "multiple_choice",
        "options": ["Not at all", "Slightly", "Very", "Completely"],
        "weight": 1.0,
        "order": 9,
    },
    {
        "id": "mc_10",
        "text": "How manageable has your workload been this month?",
        "driver": "PA",
        "response_type": "multiple_choice",
        "options": ["Not manageable", "Difficult", "Manageable", "Easy", "Very easy"],
        "weight": 1.0,
        "order": 10,
    },
    {
        "id": "mc_11",
        "text": "How supported do you feel by leadership?",
        "driver": "MC",
        "response_type": "multiple_choice",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 11,
    },
    {
        "id": "mc_12",
        "text": "How valued do you feel by your organization?",
        "driver": "MC",
        "response_type": "multiple_choice",
        "options": ["Never", "Rarely", "Sometimes", "Often", "Always"],
        "weight": 1.0,
        "order": 12,
    },
    {
        "id": "mc_13",
        "text": "How much outside stress affects your daily life?",
        "driver": "MC",
        "response_type": "multiple_choice",
        "options": ["None", "Low", "Moderate", "High", "Extreme"],
        "weight": 1.0,
        "order": 13,
    },
]
